# rag_examples.py

"""
Few-shot examples used for alloy extraction, processing condition extraction,
characterization techniques, and properties. These examples are used for
RAG-style retrieval to condition the prompts.
"""

alloy_examples = [
    "Article: It is found that both of these aforementioned alloys have hardnesses of about 420 HV, which is equated to their similar microstructures.\nAnswer: -",
    "Article: A multi-phase region can have multiple crystal structures like FCC+BCC or BCC+HCP etc. The as-cast AlCoCrCuNi base alloy is found to have a dendritic structure, of which only solid solution FCC and BCC phases can be observed.\nanswer: AlCoCrCuNi",
    "Article: AlCrFeCoNiCuTi alloy contains BCC1 phase, BCC2 phase, and a FCC phase. AlCrFeCoNiCuV alloy contains two different phases with BCC, FCC structure, respectively.\nAnswer: AlCrFeCoNiCuTi, AlCrFeCoNiCuV",
    "Article: AlxTi(x=1,x=2,x=3) are a class of alloys used for various applications.\nAnswer: AlTi, Al2Ti, Al3Ti.",
    "Article: The multiprincipal CoCrFeNiCuAl high-entropy alloy is the most widely studied high-entropy alloy system in the past decade [9–10]. In this paper, the equiatomic CoCrFeNiCuAl alloy was prepared by vacuum arc melt casting and the as-cast alloy was subsequently heated for 2 h at 1000 ◦C.\nAnswer: CoCrFeNiCuAl",
    "Article: AlxCoCrFeNi alloys with multiprincipal elements (x values in a molar ratio of 1, 1.5, 2, 2.5 and 3) are prepared by using an arc-melting plus casting method.\nAnswer: AlCoCrFeNi, Al1.5CoCrFeNi, Al2CoCrFeNi, Al2.5CoCrFeNi, Al3CoCrFeNi.",
    "Article: The AlCrFeNiMox (x = 0, 0.2, 0.5, 0.8, 1.0) high entropy alloys were produced by vacuum arc melting, and their microstructure and mechanical properties were investigated. AlCrFeNi, AlCrFeNiMo0.2, and AlCrFeNiMo0.5 alloys contained two body centered cubic (BCC) phases which were AlNi-type intermetallic compound and FeCr-type solid solution.\nanswer: AlCrFeNi, AlCrFeNiMo0.2, AlCrFeNiMo0.5, AlCrFeNiM0.8, AlCrFeNiMo.",
    "Article: A five component Fe20Cr20Mn20Ni20Co20 alloy forms a single fcc solid solution which solidifies dendritically.\nAnswer: Fe20Cr20Mn20Ni20Co20.",
    "Article: In this study, an AlTiCrFeNiCu high entropy alloy (HEA) was synthesized by vacuum arc furnace in high purity argon atmosphere. The heat resistance of this HEA was investigated by using a differential scanning calorimeter (DSC) and a chamber type electric resistance furnace.\nAnswer: AlTiCrFeNiCu.",
    "Article: Al23Co15Cr23Cu8Fe15Ni16 and Al8Co17Cr17Cu8Fe17Ni33 high entropy alloys were investigated by scanning electron microscopy, transmission electron microscopy and three dimensional atom probe.\nanswer: Al23Co15Cr23Cu8Fe15Ni16, Al8Co17Cr17Cu8Fe17Ni33.",
    "Article: Inequi-atomic CoNiFeCrAl0.6Ti0.4 high entropy alloy has been designed and fabricated by mechanical alloying (MA) and spark plasma sintering (SPS).\nanswer: CoNiFeCrAl0.6Ti0.4",
    "Article: Inequi-atomic CoNiFeCrAl0.6Ti0.4 high entropy alloy has been designed and fabricated by mechanical alloying (MA) and spark plasma sintering (SPS).\nanswer: CoNiFeCrAl0.6Ti0.4.",
    "Article: The corrosion behavior of FeCoNiCrCux high-entropy alloys in 3.5% NaCl solution is reported in this paper. The alloys used in this study were FeCoNiCr (x = 0), FeCoNiCrCu0.5 (x = 0.5) and FeCoNiCrCu (x = 1).\nAnswer: FeCoNiCr, FeCoNiCrCu0.5, FeCoNiCrCu.",
    "Article: A series of AlCoCrCuNiTiYx (x values in molar ratio, x = 0, 0.5, 0.8, 1.0) alloys have been prepared using vacuum arc melting. Classical high entropy diffraction peaks corresponding to a BCC crystal structure and some Cu, Cr peaks are observed for the AlCoCrCuNiTi alloy.\nAnswer: AlCoCrCuNiTi, AlCoCrCuNiTiY0.5, AlCoCrCuNiTiY0.8, AlCoCrCuNiTiY",
    "Article: CoCrFeNiAlxCu1−x x: molar ratio; x= 0, 0.25, 0.5, 0.75, and 1, denoted by SCA1, SCA2, SCA3, SCA4, and SCA5, respectively alloys were prepared by arc melting pure metal mixtures in a high-purity argon atmosphere.\nAnswer: CoCrFeNiCu, CoCrFeNiAl0.25Cu0.75, CoCrFeNiAl0.5Cu0.5, CoCrFeNiAl0.75Cu0.25, CoCrFeNiAl.",
    "Article: A high entropy alloy of Ti0.5CrFeNiAlCo can form two BCC crystal structures, one is with larger lattice parameter, and another with smaller one. In this paper, more Co was added in the Ti0.5CrFeNiAlCo alloy to detect the crystal structure and the properties changes. It is found that, with the increase of Co addition, the smaller BCC prefers to transit to FCC firstly, and the compressive strength deceased slightly.\nAnswer: Ti0.5CrFeNiAlCo",
    "Article: Mn, Ti and V were added in an equal-molar ratio to the AlCrFeCoNiCu alloy and the effects of these added elements on microstructure and properties of AlCrFeCoNiCu high entropy alloy were studied.\nAnswer: AlCrFeCoNiCu.",
    "Article: Two promising high-entropy alloys (HEAs) AlxCrFe1.5MnNi0.5 (x = 0.3 and 0.5) were designed from Al–Co–Cr–Cu–Fe–Ni alloys by substituting Mn for expensive Co and excluding Cu to avoid Cu segregation.\nanswer: Al0.3CrFe1.5MnNi0.5, Al0.5CrFe1.5MnNi0.5.",
    "Article: Effects of Cr content on microstructures and hot hardness of AlCoCrxFeMo0.5Ni high-entropy alloys (x = 0–2.0) were investigated.\nAnswer: AlCoFeMo0.5Ni, AlCoCr0.5FeMo0.5Ni, AlCoCrFeMo0.5Ni, AlCoCr1.5FeMo0.5Ni, AlCoCr2FeMo0.5Ni.",
    "Article: The present study is focused on synthesis and mechanical properties characterization of equiatomic CoCrNi medium entropy alloy (MEA).\nAnswer: CoCrNi.",
    "Article: An equiatomic NiFeCrCoMn alloy, two non-equiatomic NiFeCrCoMn alloys optimized for low stacking fault energy, and an equiatomic NiFeCrCo alloy were produced by arc melting.\nAnswer: NiFeCrCoMn, NiFeCrCo",
    "Article: A new refractory alloy, Ta20Nb20Hf20Zr20Ti20, produced by vacuum arc-melting followed by hot isostatic pressing (HIPing) at T = 1473 K and P = 207 MPa for 3 h has predominantly a single-phase body-centered cubic (BCC) structure with the lattice parameter a = 340.4 pm.\nAnswer: Ta20Nb20Hf20Zr20Ti20",
    "Article: The microstructure was analyzed by scanning electron microscopy (SEM) using a Quanta 600F scanning electron microscope (FEI, North America NanoPort, Hillsboro, OR) equipped with backscatter electron (BSE), energy-dispersive X-ray spectroscopy (EDS) and electron backscatter diffraction (EBSD) detectors.\nAnswer: -",
    "Article: With an aim to understand the great reduction in the X-ray diffraction (XRD) intensities of high-entropy alloys, a series of Cu–Ni–Al–Co–Cr–Fe–Si alloys with systematic addition of principal elements from pure element to seven elements was investigated for quantitative analysis of XRD intensities.\nAnswer: -",
    "Article: The microstructure and compressive properties of Alx(TiVCrMnFeCoNiCu)100-x (x=0, 11.1, and 20 at.%) high-entropy alloys were studied. With the increase of Al content, the number of phases in the alloys gradually decreases. When Al content is 20at.%, only bcc solid-solution structure is found in the alloy.\nAnswer: Ti12.5V12.5Cr12.5Mn12.5Fe12.5Co12.5Ni12.5Cu12.5, Al11.1Ti11.1V11.1Cr11.1Mn11.1Fe11.1Co11.1Ni11.1Cu11.1, Al20Ti2.5V2.5Cr2.5Mn2.5Fe2.5Co2.5Ni2.5Cu2.5",
    "Article: Alloy ingots with a nominal composition of (FeCoNiCrMn)100-xAlx(x=0,10 and 20at.%) were synthesized by arc-melting a mixture of pure metals (purity >99wt.%) in a Ti-gettered high-purity argon atmosphere.\nAnswer: Fe20Co20Ni20Cr20Mn20, Fe18Co18Ni18Cr18Mn18Al10, Fe16Co16Ni16Cr16Mn16Al20",
]


processing_condition_examples = [
    "Article: The as-cast AlCoCrCuNi base alloy is found to have a dendritic structure, of which only solid solution FCC and BCC phases can be observed.\nAnswer: As-Cast",
    "Article: AlCoCrCuFe after MA at 900 ◦C has a BCC structure.\nAnswer: Mechanically alloyed.",
    "Article: NiCoCrCuFe after Spark Plasma Sintering at 900 ◦C leads to the formation of a sigma phase.\nAnswer: Spark Plasma Sintering",
    "Article: It can be seen that the AlAuCoCrCuNi alloy is composed of FCC and AuCu phases.\nAnswer: -",
    "Article: AlCoCuCrFeNi is prepared by arc melting and casting at 700 K.\nAnswer: Arc Melted",
    "Article: The multi-component AlCoCrCuFeNi alloy was produced by melting the constituent elements in an equiatomic ratio in an induction levitation furnace. The furnace was operated at 10.8kW, with a frequency of 200kHz. Melting and casting were performed in a pure argon atmosphere in a copper crucible. Repeated melting was carried out at least five times to improve the chemical homogeneity of the alloy.\nAnswer: Melting and casting in argon atmosphere, repeated melting, 10.8kW, 200kHz",
    "Article: As-cast alloys were homogenized at 1100°C for 4h and air cooled. The alloys were then aged at 800°C for 10h followed by air cooling.\nAnswer: Homogenized at 1100°C for 4h, aged at 800°C for 10h, air cooled",
    "Article: Samples were annealed at 1000°C for 6h, water quenched, and cold rolled. The rolling reduction was 84%, with a final thickness of 3mm.\nAnswer: Annealed at 1000°C for 6h, water quenched, cold rolled, 84% reduction, 3mm thickness",
    "Article: The equiatomic CoCrFeNiCuAl alloy was prepared by vacuum arc melt casting and the as-cast alloy was subsequently heated for 2 h at 1000 ◦C.\nAnswer: Vacuum arc melted and annealed for 2h at 1000 ◦C",
    "Article: AlxCoCrFeNi alloys are prepared by a vacuum furnace under argon atmosphere. The rod ingot of the alloy with a diameter of 6 mm is obtained in a cold copper hearth.\nAnswer: Vacuum melted under argon atmosphere",
    "Article: AlTiCrFeNiCu was prepared by vacuum arc melting with electromagnetic stir from a mixture of pure bulk metals (purity better than 99 wt%) in high-purity argon atmosphere and solidified in a water-cooled copper mould.\nAnswer: Vacuum arc melted",
    "Article: Experimental methods and thermodynamic calculations: Thermodynamic calculations were performed using the software Pandat Version 8 (CompuTherm LLC, Madison, WI, USA) and the thermodynamic database SGTE SSOL4[14]. Further details of the calculations are given in Section3.2\nAnswer: -",
    "Article: The microstructure was analyzed by scanning electron microscopy (SEM) using a Quanta 600F scanning electron microscope (FEI, North America NanoPort, Hillsboro, OR) equipped with backscatter electron (BSE), energy-dispersive X-ray spectroscopy (EDS) and electron backscatter diffraction (EBSD) detectors.\nAnswer: -",
    "Article: Experimental procedures.Materials and sample preparation: To remove as many surface imperfections as possible, the samples were polished on a Buehler rotating grinder and polisher.\nAnswer: -",
    "Article: Microstructural features of the tensile regions of the fatigue samples were analyzed, using back-scattered electron microscopy (BSE), to determine the homogeneity of the microstructures.\nAnswer: -",
    "Article: CoNiFeCrAl0.6Ti0.4 (in atomic proportion) high entropy alloy was prepared by 45 h dry milling of mixed elemental powders. All the sintering, the samples were heated to 600 C within 4 min.\nAnswer: Powder metallurgy and sintered at 600 C for 4 min",
    "Article: The alloys used in this study were FeCoNiCr (x = 0), FeCoNiCrCu0.5 (x = 0.5) and FeCoNiCrCu (x = 1). These alloys were melted by arc melting from a mixture of high purity (99.99%) of Fe, Co, Ni, Cr, and Cu metals under a titanium-gettered atmosphere of argon. For comparison, AISI 304L stainless steel was also used in this study.\nAnswer: Arc melted",
    "Article: Alloy ingots with nominal composition of Ti0.5CrFeNiAlCox (x: molar ratio, x = 1, 1.5, 2, 3, denoted by Co1, Co1.5, Co2 and Co3, respectively) were prepared by arc melting mixtures of commercial-purity metals (purity better than 99 wt%) in a Ti-gettered high-purity argon atmosphere. The alloys were re-melted several times to improve homogeneity.\nAnswer: Arc melted in Argon atmosphere and re-melted several times to get homogeneity",
    "Article: This study comprises the microstructure characterization of four as-cast CoCrFeNiAl0.3, CoCrFeNiTi0.3, CoCrFeNiMo0.3 and CoCrFeNiAl0.3Mo0.1 FCC high entropy alloys. A small vacuum arc-melting furnace with a water-cooled copper crucible was employed to synthesize the alloys under 0.2atm of Ti-gettered high-purity argon atmosphere.\nAnswer: Vacuum arc-melted and as cast",
    "Article: AlCrFeCoNiCu, AlCrFeCoNiCuMn, AlCrFeCoNiCuTi and AlCrFeCoNiCuV (nominal compositions is equimolar) alloy ingots were prepared by vacuum arc melting the mixtures of pure metals with purities of better than 99.9 mass%, in a Ti-gettered high-purity argon atmosphere.\nAnswer: Vacuum arc melted",
    "Article: Raw elemental material, Al, Co, Cr, Fe, and Ni with purity higher than 99 wt % and master alloy, Fe-61.5 wt % Mo, were melted to prepare the alloys by using arc-melting method under argon atmosphere. Four times of re-melting and re-solidification were performed for each sample to ensure the uniformity in composition.\nAnswer: Arc-melted under argon atmosphere",
    "Article: Inequi-atomic CoNiFeCrAl0.6Ti0.4 high entropy alloy has been designed and fabricated by mechanical alloying (MA) and spark plasma sintering (SPS). Alloying behavior, microstructure, phase evolution and mechanical properties of CoNiFeCrAl0.6Ti0.4\nAnswer: Mechanical alloyed and Spark Plasma Sintering"
]


characterization_examples = [
    "Article: The splat-quenched and as-cast materials were characterized by different techniques such as XRD, SEM, TEM and 3D-AP. XRD spectra were measured with Cu Kα radiation in the θ–2θ configuration using a Bruker AXS, D8 diffractometer. Thin-foil specimens suitable for TEM observations were prepared by mechanical thinning down to a thickness of 20μm followed by Ar-ion milling.\nAnswer: XRD, SEM, TEM, 3D-AP",
    "Article: The microstructure of the samples was characterized by TEM in a Philips CM30 operated at 300kV equipped with an energy dispersive X-ray (EDX) spectrometer.\nAnswer: TEM, EDX",
    "Article: High energy X-ray diffraction (XRD) was performed at the Advanced Photon Source (APS) using the 11-ID beamline located at the Argonne National Laboratory to obtain diffraction patterns of the sample for structural characterizations.\nAnswer: High energy XRD",
    "Article: The work has focused on microstructure investigations. X-ray diffraction (XRD), transmission electron microscopy (TEM) and three-dimensional atom probe (3D-AP) were used for this study.\nAnswer: XRD, TEM, 3D-AP",
    "Article: Fig. 1 shows the XRD patterns of CoNiFeCrAl0.6Ti0.4 high entropy alloy powder with different milling time. Microstructural analysis was employed by a Zeiss Supra 40 (Carl Zeiss NTS GmbH, Germany) scanning electron microscope (SEM).were observed under a transmission electron microscope (200 kV TEM, JEM-2100, JEOL, Tokyo, Japan) with selected area electron diffraction (SAED) analysis.\nAnswer: XRD, SEM, TEM, SAED",
    "Article: The samples were then polished and etched in diluted aqua regia before examining microstructure by a scanning electron microscope (SEM, Zeiss supra 55) operated at secondary electron mode and with an accelerating voltage of 15 kV. Chemical compositions of different phases were analyzed by SEM energy dispersive spectrometry (EDS), and the crystal structure of as-cast samples was characterized by an X-ray diffractometer (XRD, EMPYREAN with Cu radiation target) with the 2h scan ranging from 20 to 100 at a speed of 4/min.\nAnswer: SEM, EDS, XRD",
    "Article: The composition analyses of elements within these alloys were carried out by scanning electron microscope (SEM) equipped with an energy dispersive X-ray spectrometry (EDX). X-ray diffraction (XRD) using Cu K radiation was used to identify crystalline phases and obtain the lattice parameters of these alloys.\nAnswer: SEM, EDX, XRD",
    "Article: A Hitachi S-3400 N scanning electron microscope (SEM) equipped with an EDAX energy-dispersive X-ray (EDX) spectrometer was used for microstructural observation, phase composition identification and fractured surfaces observation.\nAnswer: SEM, EDX, EDAX",
    "Article: The microstructure was characterized by x-ray diffraction XRD. The thin-foil specimens were observed using high resolution transmission electron microscope HRTEM.\nAnswer: XRD, HRTEM",
    "Article: Samples were sectioned and polished for microstructural and compositional characterisation and hardness testing, using an Olympus OM-2 optical microscope, Philips 501 scanning electron microscope (SEM), Cameca Comebacks electron probe microanalyzer (EPMA), Philips PW 1050 X-ray diffractometer (XRD), and Vickers microhardness tester model UHT-1 with 10 g load.\nAnswer: SEM, EPMA, XRD",
    "Article: The fracture surface and the morphology of alloys were examined by scanning electron microscope (SEM) equipped with energy-dispersive X-ray spectrometer (EDX).\nAnswer: SEM, EDX",
    "Article: They were then etched with aqua regia, and examined using a scanning electron microscope, JEOL-5410, and its EDS analyzer.\nAnswer: EDS",
    "Article: Microstructure and compositions were analyzed with a scanning electron microscope (SEM, JEOL-5410) attached with X-ray energy dispersive spectrometer (SEM-EDS).\nAnswer: SEM, SEM-EDS",
    "Article: SEM analysis of the fracture surfaces and gage surfaces was done using the aforementioned SEM. Atomic force microscopy (AFM) analysis of gage surfaces was done using a Bruker Dimension 3000 in intermittent contact (tapping) mode and MikroMasch RiteProbe TSP1 tip.\nAnswer: SEM, AFM",
    "Article: The crystal structure of the samples was characterized by Rigaku Ultima III X-ray diffractometer (XRD). The magnetic properties were conducted on the ADE Model 4 HF vibrating sample magnetometer (VSM).\nAnswer: XRD",
    "Article: To avoid melting of potential low-melting phases/interdendritic regions in the as-cast alloys, the annealing temperatures were kept below the lowest endothermic peak observed during heating in a differential scanning calorimeter (DSC).\nAnswer: -",
    "Article: Experimental methods and thermodynamic calculations: Thermodynamic calculations were performed using the software Pandat Version 8 (CompuTherm LLC, Madison, WI, USA) and the thermodynamic database SGTE SSOL4[14]. Further details of the calculations are given in Section 3.2.\nAnswer: -",
    "Article: The CrNbTiZr and CrNbTiVZr alloys contain a disordered bcc phase and an ordered Laves phase. The lattice parameters and compositions of the identified phases are reported.\nAnswer: -",
    "Article: Research was performed on an Al0.5CoCrCuFeNi high entropy alloy (HEA) in an attempt to study the fatigue behavior.\nAnswer: -",
    "Article: Experimental procedures. Materials and sample preparation: To remove as many surface imperfections as possible, the samples were polished on a Buehler rotating grinder and polisher. 240, 400, 600, and 1200 grits were used in that order. The sample was turned through 90° after each polishing step, finishing with the 1200 grit running parallel along the length direction of the sample.\nAnswer: -",
    "Article: The microstructure and chemical composition of the alloys, the wear surface and wear debris were analyzed using a scanning electron microscope (SEM; JEOL JSM-5410) with an attached X-ray energy dispersive spectrometer (EDS). Room-temperature macro and microhardness measurements were performed using Mitutoyo HV-115 and HM-115 hardness testing machines with loads of 5 and 25g, respectively.\nAnswer: SEM, EDX",
    "Article: The ingots were solidified in flowing argon, which provided a cooling rate of 10–20Ks−1. The solidified ingots were 20mm in diameter and 20mm thick, and were cut into thin pieces 2mm thick for characterization.\nAnswer: -",
    "Article: Experimental details: Nanohardness and indentation elastic modulus of the splat-quenched and as-cast HE alloys were measured using a Fischer Picodentor HM500. The measurements were carried out at a load of 300mN for 20s. For comparison, the microhardness of as-cast HE alloy was also measured using a Reichert-Jung MHT-10 micro hardness tester, applying a load of 890N for 10s.\nAnswer: -",
    "Article: These nanoparticles are multi-elemental solid solutions instead of inter-metallic compounds, and the crystal structure possesses both the ordered L12 and the disordered FCC structures.\nAnswer: -",
    "Article: The phase structure of face-centered cubic (FCC) transits to body-centered cubic (BCC).\nAnswer: -",
    "Article: The BCC phase particles that precipitated from the supersaturated matrix and Cu-rich phases between 300°C and 600°C rendered the alloy of interest harder but more brittle. The Al0.5CoCrCuFeNi (subscripts mean molar ratio) alloy was prepared by arc-melting and casting in a vacuum chamber.\nAnswer: -"
]

properties_examples = [
    "Article: Nanohardness and indentation elastic modulus of the splat-quenched and as-cast HE alloys were measured using a Fischer Picodentor HM500. The measurements were carried out at a load of 300mN for 20s.\nAnswer: Nanohardness, Elastic Modulus",
    "Article: The fatigue properties of the HEA samples were evaluated using a cyclic loading test.\nAnswer: Fatigue",
    "Article: Room-temperature macro and microhardness measurements were performed using Mitutoyo HV-115 and HM-115 hardness testing machines with loads of 5 and 25g, respectively.\nAnswer: Macrohardness, Microhardness",
    "Article: The compression faces of the samples were paralleled by mechanical polishing and lubricated with boron nitride for elevated temperature tests. Compression tests were conducted at 600 °C, 800 °C, 1000 °C, 1200 °C, 1400 °C and 1600 °C in a computer-controlled Instron (Instron, Norwood, MA) mechanical testing machine outfitted with a Brew vacuum furnace and silicon carbide platens.\nAnswer: -",
    "Article: It is suggested that the formation of nanoparticles is dominated by the effects of the high mixing entropy.\nAnswer: -",
    "Article: The Al0.3CoCrFeNi and Al0.3CoCrFeNiTi0.1 alloys were hardened by massive (Ni,Al)-rich and (Ni,Co,Ti)-rich B2 ordered precipitates, respectively. The large age hardening of the Al0.3CoCrFeNiMo0.1 alloy is attributed to the precipitation of both fine (Ni,Al)-rich phase and heavy blocky (Cr,Mo)(Co,Fe,Ni) σ phase.\nAnswer: -",
    "Article: the wear surface and wear debris were analyzed using a scanning electron microscope (SEM; JEOL JSM-5410) with an attached X-ray energy dispersive spectrometer (EDS).\nAnswer: Wear resistances",
    "Article: same room temperature crystal structure and comparable size/electronegativity.\nAnswer: Electronegativity",
    "Article: Weibull models were applied to predict the fatigue data and to characterize the variability seen in the HEAs.\nAnswer: Fatigue",
    "Article: The specimens were tested to failure to determine the yield strength, ultimate tensile strength (UTS), and percent elongation.\nAnswer: Yield Strength, UTS, Percent elongation (Ductility)",
    "Article: Immersion tests were conducted in aerated 3.5% NaCl solution at 25 ◦C for 30 days. To remove adherent corrosion products after immersion tests, the corroded specimens were cleaned in 10% HCl solution with 1 g L−1 hexamethylenetetramine followed by distilled water and acetone.\nAnswer: Corrosion resistances",
    "Article: Fig. 3 shows the maximum stress and compressibility of AlCoCrCuNiTiYx alloy. The compressive strength and plastic strain limit of AlCoCrCuNiTi alloy are 1495 MPa and 7.68% respectively. It exhibits high compressibility and high plastic deformability.\nAnswer: Compressive Strength",
    "Article: It is found that, with the increase of Co addition, the smaller BCC prefers to transit to FCC firstly, and the compressive strength decreases slightly.\nAnswer: Compressive Strength",
    "Article: Prior rolling on the alloys before aging could significantly enhance the age-hardening rate and hardness level due to introduced defects. Al0.5CrFe1.5MnNi0.5 alloy exhibits excellent oxidation resistance up to 800 ◦C, which is better than Al0.5CrFe1.5MnNi0.5 alloy. Combining this merit with its high softening resistance and wear resistance as compared to commercial alloys, Al0.5CrFe1.5MnNi0.5 alloy has the potential for high-temperature structural applications.\nAnswer: Hardness, Oxidation Resistance, Wear Resistance",
    "Article: The alloy hardness increases from Hv 601 at x = 0 to Hv 867 at x = 2.0 as a result of increasing the amount of hard phase. All the AlCoCrxFeMo0.5Ni alloys possess higher hot-hardness level than that of Ni-based superalloys.\nAnswer: Hardness, Hot hardness",
    "Article: Samples annealed at a moderate temperature near their recrystallization temperature (625–675 1C) and 1100 1C were cut into flat tensile samples and tested at a strain rate of 7.3  104 s1. Equiatomic NiFeCrCo had the highest ductility and toughness after annealing at both temperatures, followed by Ni18.5Fe18.5Cr18.5-Co26Mn18.5. Ni14Fe20Cr26Co20Mn20 exhibited poor thermal stability, forming σ-phase intermetallics at temperatures below 1100 1C.\nAnswer: Ductility, Toughness, Thermal Stability",
    "Article: The heat resistance of this HEA was investigated by using a differential scanning calorimeter (DSC) and a chamber type electric resistance furnace.\nAnswer: Heat resistance",
    "Article: The yield stress, compressive strength, compression ratio and Vickers hardness of the alloy are 2.08, 2.52 GPa, 11.5% and 573 HV, respectively.\nAnswer: Yield stress, Compressive Strength, Compression ratio, Vickers hardness",
    "Article: The as-annealed alloy exhibits high strength and excellent ductility of 1.63 GPa and 34%, respectively. Both alloys possess high saturated magnetization and undergo a ferromagnetic transition.\nAnswer: Strength, Ductility, Magnetization",
    "Article: Alloys exhibit a transition temperature higher than that of Co-based alloy T-800 by about 200 K and have respective hardness values, Hv 374 and Hv 450 at 1273 K, being much higher than those, around Hv 127, of In 718 and In 718 H. The mechanism of larger strengthening and softening resistance is related with B2 and phases, both having multi-principal-element effects.\nAnswer: Hardness, Strength",
    "Article: The microstructure of Al8Co17Cr17Cu8Fe17Ni33 is mainly characterized by two phases. Nano-sized precipitates enriched mainly in Ni are embedded in a matrix depleted in Al and Cu. The phases observed in both high entropy alloys are compared with the equilibrium phases predicted by Thermo-Calc simulation.\nAnswer: -",
    "Article: The increase of x leads to distortion of the crystalline lattice and the alloy strengthening. The hardness of the alloys increases with x while the highest hardness (740 HV) is achieved when x = 3.\nAnswer: Hardness, Strength",
    "Article: It is found that, the content of Cu, Ni and Al decreased badly in the surface of as cast AlTiCrFeNiCu after immersed in the water solution of 5% HCl for 7 days. The compressive fracture strength of as cast AlTiCrFeNiCu HEA was 1219 MPa. The high compressive strength may owe to the solid solution strengthening from multi elements.\nAnswer: Fracture Strength",
    "Article: The alloy density and Vickers microhardness are  = 9.94 g/cm3 and Hv = 3826 MPa. The alloy has high compression yield strength (0.2 = 929 MPa) and ductility (ε > 50%).\nAnswer: Density, Vickers microhardness, Yield Strength, Ductility"
]

